name: Push and pull request devel

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  test:
    uses: .github/workflows/test.yml

  format:
    needs: test
    uses: .github/workflows/format.yml
