name: Clang-format

on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Formatting
        run: echo "formatting..."
