name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: isshlyapin/ros2:1.3
      volumes:
        - /etc/localtime:/etc/localtime

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build
        
      - name: Run tests
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
