name: Test

on:
    workflow_call:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test1
        run: echo "Test1 success"

      - name: Test2
        run: echo "Test2 success"
        
      - name: Test3
        run: echo "Test3 success"
        
      - name: Test5
        run: echo "Test4 success"
